#!/bin/bash
# WebForge Bootstrap Script
# Run this after WebForge generates your project to install dependencies and set up the project
# Usage: bash scripts/bootstrap.sh [project-name]

set -e

PROJECT_NAME=${1:-"my-webforge-app"}

echo "🔨 WebForge Bootstrap"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Project: $PROJECT_NAME"
echo ""

# Check node version
NODE_VERSION=$(node -v 2>/dev/null | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt "18" ]; then
  echo "❌ Node.js 18+ required. Current: $(node -v)"
  exit 1
fi

echo "✅ Node.js: $(node -v)"

# Check if src/ exists (generated by agents)
if [ ! -d "src" ]; then
  echo ""
  echo "⚠️  No src/ directory found."
  echo "   Run /new-app in OpenCode first, then run this script."
  echo ""
  echo "   Alternatively, scaffold a new Vite project:"
  echo "   npm create vite@latest $PROJECT_NAME -- --template react-ts"
  exit 1
fi

# Install dependencies
echo ""
echo "📦 Installing dependencies..."
npm install

# Install core runtime deps
echo ""
echo "📦 Installing React ecosystem..."
npm install \
  react-router-dom \
  @tanstack/react-query \
  zustand \
  react-hook-form \
  zod \
  @hookform/resolvers \
  axios \
  clsx \
  tailwind-merge \
  class-variance-authority \
  lucide-react \
  sonner

# Install dev deps
echo ""
echo "🔧 Installing dev dependencies..."
npm install -D \
  tailwindcss \
  @tailwindcss/forms \
  postcss \
  autoprefixer \
  @types/node \
  vitest \
  @testing-library/react \
  @testing-library/jest-dom \
  @playwright/test

# Setup Tailwind if not configured
if [ ! -f "tailwind.config.ts" ]; then
  echo ""
  echo "🎨 Setting up Tailwind CSS..."
  npx tailwindcss init -p --ts
fi

# Setup shadcn/ui
echo ""
echo "🧩 Setting up shadcn/ui..."
echo "Run: npx shadcn@latest init"
echo "(Choose: TypeScript ✓, Default style, Neutral color, CSS variables ✓)"
echo ""
read -p "Run shadcn init now? (y/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
  npx shadcn@latest init
  # Add common components
  npx shadcn@latest add button card input textarea select \
    table badge tabs dialog sheet dropdown-menu \
    separator skeleton toast form label
fi

# Copy env example
if [ -f ".env.example" ] && [ ! -f ".env.local" ]; then
  cp .env.example .env.local
  echo ""
  echo "📋 Created .env.local from .env.example"
  echo "   ⚠️  Edit .env.local with your actual values before running"
fi

# Type check
echo ""
echo "🔍 Running type check..."
if npx tsc --noEmit 2>&1 | grep -q "error TS"; then
  echo "⚠️  TypeScript errors found. Run 'npm run type-check' for details."
else
  echo "✅ TypeScript: OK"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Bootstrap complete!"
echo ""
echo "Next steps:"
echo "  1. Edit .env.local with your API URL and credentials"
echo "  2. npm run dev"
echo "  3. Open http://localhost:5173"
echo ""
echo "Available commands:"
echo "  npm run dev          — Start dev server"
echo "  npm run build        — Production build"
echo "  npm run type-check   — TypeScript validation"
echo "  npm run lint         — ESLint check"
echo "  npm run test         — Run tests"
